- name: Install auditd package
  ansible.builtin.package:
    name: "{{ common_name_auditd }}"
    state: present

- name: Manage auditd.conf
  ansible.builtin.copy:
    src: auditd.conf
    dest: /etc/audit/auditd.conf
    mode: "0640"
  notify: restart-auditd

- name: Manage audit.rules
  ansible.builtin.copy:
    src: audit.rules
    dest: /etc/audit/rules.d/audit.rules
    mode: "0640"
  notify: restart-auditd

- name: Ensure auditd service is running
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true
  when: not partial_install
