- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: All Common Tasks
  ansible.builtin.include_tasks:
    file: "{{ task_group }}.yml"
  with_list:
    - firewall
    - baseline  # includes: sshd, apt
    # (above) Always First
    - auditd
    - ntp
    - packages
    - pam
    - security
    - sudo
    # (below) Always Last
    - users
    - cleanup
  loop_control:
    loop_var: task_group
