- name: Include name server on (service) hosts
  ansible.builtin.include_role:
    name: nameserver
  when: "'service' in ansible_hostname"

- name: Include forwarding service on (service) hosts
  ansible.builtin.include_role:
    name: forwarder
  when: "'service' in ansible_hostname"
